---
- name: "Create user, group and data folder for {{ service_name }}"
  block:
    - name: "Create group {{ service_name }}"
      group:
        name: "{{ service_name }}"
        state: present

    - name: "Create user {{ service_name }}"
      user:
        name: "{{ service_name }}"
        group: "{{ service_name }}"
        state: present
      register: create_user

    - name: Create directory $HOME/.ansible/tmp if it does not exist
      ansible.builtin.file:
        path: "/home/{{ service_name }}/.ansible/tmp"
        state: directory
        mode: "0755"
        owner: "{{ service_name }}"
        group: "{{ service_name }}"

    - name: "Create data directory for {{ service_name }}"
      ansible.builtin.file:
        path: "/data/{{ service_name }}"
        state: directory
        owner: "{{ service_name }}"
        group: "{{ service_name }}"
        mode: "0700"

    - name: Set SELinux label for database folder
      community.general.sefcontext:
        target: "/data/{{ service_name }}(/.*)?"
        setype: container_file_t
        state: present
      register: selinux_postgre_change

    - name: Apply new SELinux file context to filesystem
      command: restorecon -irv /data/{{ service_name }}

  become: true
  become_user: root
