- name: "Systemd work for {{ service_name }}"
  block:

    - name: "Copy systemd file for {{service_name }}"
      template:
        src: "systemd.service"
        dest: "/etc/systemd/system/{{ service_name }}.service"
        mode: 0644

    - name: "Enable / start {{ service_name }} service"
      systemd:
        name: "{{ service_name }}"
        state: started
        enabled: true
        daemon_reload: true

  become: true
  become_user: root
